### ISSUE TITLE
Is there any readme or demo or example?

### ISSUE THREAD

**Issue by flyq** [cryptape/cita-build#13]
I build the image of ubuntu-18.04-20191128, and don't know how to continue.

I just want to run the [cita-web3‘s examples](https://github.com/citahub/cita-common/blob/develop/cita-web3/README.md#examples).

I read the Dockerfile and the script, it just a base environment. 

When i run `docker run cita/cita-build:ubuntu-18.04-20191128`, the container exit immediately.
How to download the source code of cita-common to the container and run the example?

**Comment by Pencil-Yao** [comment]
The image is a dependence for cita compile, you don't need build it replacing of downloading from docker hub.

The image is used when you compile cita like, 
`./env.sh make release`
