### ISSUE TITLE
Miscellaneous for branch `ubuntu18`

### ISSUE THREAD

**Issue by chaoticlonghair** [cryptape/cita-build#8]
Commit-id: 1d3a851eee4606caf3b7810d87f7e4ffbfb0485e

1. Please check if `${USER_ID}` is empty before use it. (Add _quotes_ is better?)
   https://github.com/cryptape/cita-build/blob/1d3a851eee4606caf3b7810d87f7e4ffbfb0485e/entrypoint.sh#L3-L4
2. If the end user use `root` user, what happened?
    https://github.com/cryptape/cita/blob/0a9b4b476e29d213349e2d03d3bb6491f6b99f74/env.sh#L43
3. The linux user `user` (Is this name _easy to understand_?) do not have `write` permissions for his `${HOME}`.
   https://github.com/cryptape/cita-build/blob/1d3a851eee4606caf3b7810d87f7e4ffbfb0485e/Dockerfile#L3
   - Do not set `HOME` manually, [it is a system environment variable](https://www.google.com/search?q=how+to+change+%24home+in+linux).
   - Do not set `HOME` environment variable to [`/opt`](https://www.google.com/search?q=linux+directory+structure).
   - [How to choose where to install rust & cargo?](https://github.com/rust-lang-nursery/rustup.rs/blob/525adef/README.md#choosing-where-to-install)
4. Remove useless files, such as `.git` (I think, the whole `pyethereum` can be removed after `python install`) in **same layer**.
   https://github.com/cryptape/cita-build/blob/087095bdcd3446cd94ac9ef5d773410866a8b5ad/Dockerfile#L48-L53
This piece of code is very [unprofessional](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers).
5. Remove useless docker layers.
6. [Prevent messed up Git history](https://fle.github.io/git-tip-keep-your-branch-clean-with-fixup-and-autosquash.html).
   There is a PR in [`cita`](https://github.com/cryptape/cita) has more than 50 commits.
7. If install third-party softwares, the best way is to grab from the certain and trustworthy source.
    **Do not just copy executable files from unknown sources without version number and checksums.**
    For example: `gosu` has an offical [INSTALL.md](https://github.com/tianon/gosu/blob/e87cf95808a7b16208515c49012aa3410bc5bba8/INSTALL.md#from-debian). A lot of world-widely famous open source project according to it, such as [`Postgres`](https://github.com/docker-library/postgres/blob/927a8525cf80896f2bd146a1b0eff7d6ef2cb7bf/11/Dockerfile#L18-L29).
    https://github.com/cryptape/cita-build/blob/1d3a851eee4606caf3b7810d87f7e4ffbfb0485e/Dockerfile#L62-L66

**Small Rant:**

**IMO**, I think the [PR-7](https://github.com/cryptape/cita-build/pull/7) should not been merged and the [PR-6](https://github.com/cryptape/cita-build/pull/6) (this PR is closed but the new branch [`ubuntu18`](https://github.com/cryptape/cita-build/tree/ubuntu18) was base on it) can be improved.

I have **reviewed** both of them and I have **mentioned** some dubious issues.
`闻道有先后，术业有专攻`, we all have `first-time` in new field.
I'm very pleasure to point them out (in PRs) and I hope someone can benefit from them.
But no changes and no debates before them merged.

I think unimportant issues and incomplete features can be _tolerated_.
I often pull requests with some defects, too. I can not deny it.
But, those PRs have obvious bugs and uncommon usages.

**Do not just finish it**, treat it as an artwork.
Consider yourself as the creator of beautiful things.
The world is already worse enough.
A coder should have **honour** for his codes.
Let yourself **can be proud of** your works.

No one is perfect, we can not avoid bugs / issues completely, but we can do better.

**Let's make things better, together.**

**Comment by TheWaWaR** [comment]
Actually, current branch use in circleci is `ubuntu-18.04-20180523` : https://github.com/cryptape/cita-build/blob/ubuntu-18.04-20180523/Dockerfile

**Comment by TheWaWaR** [comment]
First, thanks for writing this.

**My responses**:

1. Good point, just not that patient at that time.
2. Good point, just not that patient at that time.
3. Good point, but please consider `user` is add after the docker image has been built, where to put cargo home in the first place?
4. Good point, just forgot.
5. Well, what do this even means?
6. Fine, a link please.

> But, those PRs have obvious bugs and uncommon usages.

Can agree with this, normal usages, all CI are work just fine.

Artwork, indeed, a lot more effort.

**Comment by u2** [comment]
This pr #9 and another one proposed by @TheWaWaR , only focus on the root issue and the 4th problem.

What about add a warning if using root user?

**Comment by u2** [comment]
@TheWaWaR 
The meaning of docker layer: https://stackoverflow.com/a/33836848/530473

**Comment by TheWaWaR** [comment]
Close with PR #9 , feel free to reopen this issue.
